version: '3'
services:
  database:
    image: 'postgres:latest' # use alpine official postgres version
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
  database-data: # named volumes can be managed easier using docker-compose

  # docker-compose run database bash
  # psql --host=##### --username=##### --dbname=#####